version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean package
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - mircroservice-provider/target/order-service.jar
    - mircroservice-consumer/target/order-service.jar
  discard-paths: yes